import type{GuestMessage,Invitation,Rsvp}from'../types';
const API_BASE=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');
type PublicRow={id:string;slug:string;template_slug:string;package_slug:'HEMAT'|'REGULER'|'VIP';payload:Record<string,unknown>;active_until:string|null};
type ApprovedMessageRow={id:string;sender_name:string;relationship?:string|null;attendance:'hadir'|'tidak_hadir'|'ragu';message:string;created_at:string};
export type PublicApiErrorCode='VALIDATION_ERROR'|'RATE_LIMITED'|'INVITATION_UNAVAILABLE'|'SERVICE_UNAVAILABLE'|'REQUEST_FAILED';
export class PublicApiError extends Error{constructor(public code:PublicApiErrorCode,public status:number){super(code);this.name='PublicApiError'}}
function apiError(status:number){if(status===400)return new PublicApiError('VALIDATION_ERROR',status);if(status===404)return new PublicApiError('INVITATION_UNAVAILABLE',status);if(status===429)return new PublicApiError('RATE_LIMITED',status);if(status>=500)return new PublicApiError('SERVICE_UNAVAILABLE',status);return new PublicApiError('REQUEST_FAILED',status)}
async function post(slug:string,path:string,body:unknown){const r=await fetch(`${API_BASE}/api/public/invitations/${encodeURIComponent(slug)}/${path}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw apiError(r.status);return true}
export const submitPublicRsvp=(slug:string,x:Omit<Rsvp,'id'|'invitationId'|'createdAt'>)=>post(slug,'rsvp',x);
export const submitPublicMessage=(slug:string,x:Omit<GuestMessage,'id'|'invitationId'|'isApproved'|'createdAt'>)=>post(slug,'messages',x);
export async function fetchApprovedMessages(slug:string):Promise<GuestMessage[]>{const r=await fetch(`${API_BASE}/api/public/invitations/${encodeURIComponent(slug)}/messages`,{headers:{Accept:'application/json'}});if(!r.ok)throw apiError(r.status);const d=await r.json() as{messages?:ApprovedMessageRow[]};return(d.messages||[]).map(x=>({id:x.id,invitationId:'',senderName:x.sender_name,relationship:x.relationship||undefined,attendance:x.attendance,message:x.message,isApproved:true,createdAt:x.created_at}))}
export async function fetchPublicInvitation(slug:string):Promise<Invitation|null>{const r=await fetch(`${API_BASE}/api/public/invitations/${encodeURIComponent(slug)}`,{headers:{Accept:'application/json'}});if(r.status===404)return null;if(!r.ok)throw apiError(r.status);const d=await r.json(),x=d.invitation as PublicRow,p=x.payload as any;let messages:GuestMessage[]=[];try{messages=await fetchApprovedMessages(slug)}catch(e){if(e instanceof PublicApiError&&e.code==='INVITATION_UNAVAILABLE')return null}return{id:x.id,orderId:'',userId:'',templateId:'',templateSlug:x.template_slug,packageSlug:x.package_slug,slug:x.slug,title:p.title||`${p.groomName||''} & ${p.brideName||''}`,isPublished:true,allowSearchEngines:false,activeUntil:x.active_until||undefined,quoteArabic:p.quoteArabic,quoteTranslation:p.quoteTranslation,quoteSource:p.quoteSource,musicUrl:p.musicUrl,musicTitle:p.musicTitle,customMusicUrl:p.customMusicUrl,couple:p.couple||{id:'',invitationId:x.id,groomName:p.groomName||'',groomFullName:p.groomFullName||p.groomName||'',groomFather:p.groomFather||'',groomMother:p.groomMother||'',brideName:p.brideName||'',brideFullName:p.brideFullName||p.brideName||'',brideFather:p.brideFather||'',brideMother:p.brideMother||'',createdAt:'',updatedAt:''},events:p.events||[],loveStories:p.loveStories||[],galleries:p.galleries||[],gifts:p.gifts||[],rsvps:[],guestMessages:messages,createdAt:'',updatedAt:''}}
