import React,{useState}from'react';
import{appStorage}from'../services/storage';
import{createSecureCheckout,getSecureOrderStatus}from'../services/secureCheckout';
interface Props{initialPackage?:string;initialTemplate?:string;onNavigate:(p:string)=>void}
const field='w-full rounded-lg border border-stone-300 px-3 py-2.5 text-sm';
export const SecureCheckoutPage:React.FC<Props>=({initialPackage='REGULER',initialTemplate='modern-minimalist',onNavigate})=>{const packages=appStorage.getPackages();const templates=appStorage.getTemplates().filter(t=>t.isActive);const[pkg,setPkg]=useState(initialPackage);const[tpl,setTpl]=useState(initialTemplate);const[busy,setBusy]=useState(false);const[order,setOrder]=useState<{id:string;amount:number;url:string}|null>(null);const[msg,setMsg]=useState('');const[f,setF]=useState({name:'',email:'',phone:'',slug:'',groomName:'',brideName:'',groomFullName:'',brideFullName:'',groomFather:'',groomMother:'',brideFather:'',brideMother:'',akadDate:'',akadTime:'',akadVenue:'',akadAddress:'',akadMaps:'',resepsiDate:'',resepsiTime:'',resepsiVenue:'',resepsiAddress:'',resepsiMaps:'',bankName:'',accountNumber:'',accountHolder:''});const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
const submit=async()=>{setBusy(true);setMsg('');try{const r=await createSecureCheckout({packageSlug:pkg as 'HEMAT'|'REGULER'|'VIP',templateSlug:tpl,invitationSlug:f.slug,customer:{name:f.name,email:f.email,phone:f.phone},weddingData:{groomName:f.groomName,brideName:f.brideName,groomFullName:f.groomFullName,brideFullName:f.brideFullName,groomFather:f.groomFather,groomMother:f.groomMother,brideFather:f.brideFather,brideMother:f.brideMother,akadDate:f.akadDate,akadTime:f.akadTime,akadVenue:f.akadVenue,akadAddress:f.akadAddress,akadMaps:f.akadMaps,resepsiDate:f.resepsiDate,resepsiTime:f.resepsiTime,resepsiVenue:f.resepsiVenue,resepsiAddress:f.resepsiAddress,resepsiMaps:f.resepsiMaps,bankName:f.bankName,accountNumber:f.accountNumber,accountHolder:f.accountHolder}});setOrder({id:r.orderId,amount:r.amount,url:r.redirectUrl})}catch{setMsg('Pesanan belum dapat dibuat. Periksa data atau konfigurasi pembayaran.')}finally{setBusy(false)}};
const check=async()=>{if(!order)return;setBusy(true);try{const s=await getSecureOrderStatus(order.id);if(s.is_published&&s.status==='ACTIVE')onNavigate(`/invite/${s.slug}`);else setMsg(`Status pembayaran: ${s.status}. Undangan belum diaktifkan.`)}catch{setMsg('Status belum dapat diverifikasi. Coba lagi sesaat lagi.')}finally{setBusy(false)}};
const inputs=[['name','Nama Pemesan'],['email','Email'],['phone','WhatsApp (contoh 628...)'],['slug','Slug undangan'],['groomName','Nama Panggilan Pria'],['groomFullName','Nama Lengkap Pria'],['groomFather','Ayah Mempelai Pria'],['groomMother','Ibu Mempelai Pria'],['brideName','Nama Panggilan Wanita'],['brideFullName','Nama Lengkap Wanita'],['brideFather','Ayah Mempelai Wanita'],['brideMother','Ibu Mempelai Wanita'],['akadDate','Tanggal Akad (YYYY-MM-DD)'],['akadTime','Waktu Akad'],['akadVenue','Tempat Akad'],['akadAddress','Alamat Akad'],['akadMaps','Link Maps Akad'],['resepsiDate','Tanggal Resepsi (YYYY-MM-DD)'],['resepsiTime','Waktu Resepsi'],['resepsiVenue','Tempat Resepsi'],['resepsiAddress','Alamat Resepsi'],['resepsiMaps','Link Maps Resepsi'],['bankName','Bank / E-Wallet'],['accountNumber','Nomor Rekening'],['accountHolder','Atas Nama']];
return <div className="max-w-4xl mx-auto px-4 py-10"><div className="bg-white border border-stone-200 rounded-3xl p-6 sm:p-10 shadow-sm"><p className="text-xs font-bold tracking-widest text-amber-700 uppercase">AKSARA UNDANGAN · Secure Checkout</p><h1 className="text-3xl font-bold mt-2">Pemesanan Undangan Digital</h1><p className="text-sm text-stone-600 mt-2">Pembayaran diverifikasi oleh server. Undangan tidak aktif hanya karena browser kembali dari halaman pembayaran.</p>{!order?<><div className="grid sm:grid-cols-2 gap-4 mt-8"><select className={field} value={pkg} onChange={e=>setPkg(e.target.value)}>{packages.map(p=><option key={p.id} value={p.slug}>{p.name} — Rp{p.price.toLocaleString('id-ID')}</option>)}</select><select className={field} value={tpl} onChange={e=>setTpl(e.target.value)}>{templates.map(t=><option key={t.id} value={t.slug}>{t.name}</option>)}</select>{inputs.map(([k,l])=><label key={k} className="text-xs font-semibold text-stone-700">{l}<input className={`${field} mt-1`} value={(f as any)[k]} onChange={e=>set(k,e.target.value)} /></label>)}</div><button disabled={busy} onClick={submit} className="mt-8 w-full rounded-xl bg-[#0B132B] text-white py-3.5 font-bold disabled:opacity-50">{busy?'Membuat transaksi...':'Buat Pesanan & Lanjut ke Midtrans'}</button></>:<div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><p className="font-bold">Pesanan {order.id}</p><p className="text-sm mt-1">Total server: Rp{order.amount.toLocaleString('id-ID')}</p><a className="mt-5 block text-center rounded-xl bg-[#0B132B] text-white py-3 font-bold" href={order.url}>Bayar melalui Midtrans</a><button disabled={busy} onClick={check} className="mt-3 w-full rounded-xl border border-stone-300 bg-white py-3 font-bold">{busy?'Memeriksa...':'Saya sudah membayar — Periksa Status'}</button><p className="text-xs text-stone-600 mt-3">Tombol ini hanya membaca status server; tidak dapat menandai pembayaran berhasil.</p></div>}{msg&&<p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{msg}</p>}</div></div>}
