import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { applyMidtransNotification, pool } from './db.js';
import type { MidtransNotification } from './midtrans.js';

const enabled=Boolean(process.env.DATABASE_URL);
async function seed(packageSlug:'HEMAT'|'REGULER'|'VIP'='REGULER'){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const orderId=randomUUID(),paymentId=randomUUID(),invitationId=randomUUID(),providerOrderId=`TEST-${randomUUID()}`;await pool.query(`INSERT INTO orders(id,order_number,customer_name,customer_email,customer_phone,package_slug,template_slug,gross_amount,status) VALUES($1,$2,'Test User','test@example.com','0800000000',$3,'modern-minimalist',50000,'PENDING_PAYMENT')`,[orderId,`ORD-${randomUUID()}`,packageSlug]);await pool.query(`INSERT INTO payments(id,order_id,provider_order_id,gross_amount) VALUES($1,$2,$3,50000)`,[paymentId,orderId,providerOrderId]);await pool.query(`INSERT INTO invitations(id,order_id,slug,template_slug,package_slug) VALUES($1,$2,$3,'modern-minimalist',$4)`,[invitationId,orderId,`test-${randomUUID()}`,packageSlug]);return{orderId,paymentId,providerOrderId}}
function notification(orderId:string,status:string,gross='50000.00',fraud?:string):MidtransNotification{return{order_id:orderId,status_code:'200',gross_amount:gross,signature_key:'test',transaction_status:status,...(fraud?{fraud_status:fraud}:{})}}
async function cleanup(orderId:string){if(!pool)return;const c=await pool.connect();try{await c.query('BEGIN');await c.query('DELETE FROM invitations WHERE order_id=$1',[orderId]);await c.query('DELETE FROM payment_events WHERE payment_id IN (SELECT id FROM payments WHERE order_id=$1)',[orderId]);await c.query('DELETE FROM payments WHERE order_id=$1',[orderId]);await c.query('DELETE FROM orders WHERE id=$1',[orderId]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}

test('trusted settlement activates invitation and is idempotent',{skip:!enabled},async()=>{const x=await seed();try{const first=await applyMidtransNotification(notification(x.providerOrderId,'settlement'),true);assert.equal(first.ok,true);assert.equal(first.activated,true);const second=await applyMidtransNotification(notification(x.providerOrderId,'settlement'),true);assert.equal(second.ok,true);assert.equal(second.activated,false);const state=await pool!.query(`SELECT o.status,i.is_published,i.active_until,p.paid_at,(SELECT count(*)::int FROM payment_events e WHERE e.payment_id=p.id) event_count FROM orders o JOIN payments p ON p.order_id=o.id JOIN invitations i ON i.order_id=o.id WHERE o.id=$1`,[x.orderId]);assert.equal(state.rows[0].status,'ACTIVE');assert.equal(state.rows[0].is_published,true);assert.ok(state.rows[0].active_until);assert.ok(state.rows[0].paid_at);assert.equal(state.rows[0].event_count,2)}finally{await cleanup(x.orderId)}});
test('amount mismatch fails closed without mutating payment state',{skip:!enabled},async()=>{const x=await seed();try{const result=await applyMidtransNotification(notification(x.providerOrderId,'settlement','50001.00'),true);assert.deepEqual(result,{ok:false,code:'AMOUNT_MISMATCH'});const state=await pool!.query(`SELECT o.status,p.paid_at,(SELECT count(*)::int FROM payment_events e WHERE e.payment_id=p.id) event_count FROM orders o JOIN payments p ON p.order_id=o.id WHERE o.id=$1`,[x.orderId]);assert.equal(state.rows[0].status,'PENDING_PAYMENT');assert.equal(state.rows[0].paid_at,null);assert.equal(state.rows[0].event_count,0)}finally{await cleanup(x.orderId)}});
test('non-settlement cannot regress an already active order',{skip:!enabled},async()=>{const x=await seed('VIP');try{await applyMidtransNotification(notification(x.providerOrderId,'settlement'),true);const result=await applyMidtransNotification(notification(x.providerOrderId,'cancel'),false);assert.equal(result.ok,true);if(result.ok)assert.equal(result.ignored,true);const state=await pool!.query(`SELECT o.status,i.is_published,i.active_until FROM orders o JOIN invitations i ON i.order_id=o.id WHERE o.id=$1`,[x.orderId]);assert.equal(state.rows[0].status,'ACTIVE');assert.equal(state.rows[0].is_published,true);assert.equal(state.rows[0].active_until,null)}finally{await cleanup(x.orderId)}});
test('terminal failure marks pending order failed without publishing invitation',{skip:!enabled},async()=>{const x=await seed();try{const result=await applyMidtransNotification(notification(x.providerOrderId,'expire'),false);assert.equal(result.ok,true);const state=await pool!.query(`SELECT o.status,i.is_published,p.transaction_status,p.paid_at,(SELECT count(*)::int FROM payment_events e WHERE e.payment_id=p.id) event_count FROM orders o JOIN payments p ON p.order_id=o.id JOIN invitations i ON i.order_id=o.id WHERE o.id=$1`,[x.orderId]);assert.equal(state.rows[0].status,'FAILED');assert.equal(state.rows[0].is_published,false);assert.equal(state.rows[0].transaction_status,'expire');assert.equal(state.rows[0].paid_at,null);assert.equal(state.rows[0].event_count,1)}finally{await cleanup(x.orderId)}});
test('verified delayed settlement recovers a previously failed order',{skip:!enabled},async()=>{const x=await seed();try{await applyMidtransNotification(notification(x.providerOrderId,'expire'),false);const settled=await applyMidtransNotification(notification(x.providerOrderId,'settlement'),true);assert.equal(settled.ok,true);assert.equal(settled.activated,true);const state=await pool!.query(`SELECT o.status,i.is_published,i.active_until,p.transaction_status,p.paid_at,(SELECT count(*)::int FROM payment_events e WHERE e.payment_id=p.id) event_count FROM orders o JOIN payments p ON p.order_id=o.id JOIN invitations i ON i.order_id=o.id WHERE o.id=$1`,[x.orderId]);assert.equal(state.rows[0].status,'ACTIVE');assert.equal(state.rows[0].is_published,true);assert.ok(state.rows[0].active_until);assert.equal(state.rows[0].transaction_status,'settlement');assert.ok(state.rows[0].paid_at);assert.equal(state.rows[0].event_count,2)}finally{await cleanup(x.orderId)}});
test.after(async()=>{if(pool)await pool.end()});
