import { CopyObjectCommand, DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
function config(){const endpoint=process.env.MEDIA_STORAGE_ENDPOINT,bucket=process.env.MEDIA_STORAGE_BUCKET,accessKeyId=process.env.MEDIA_STORAGE_ACCESS_KEY,secretAccessKey=process.env.MEDIA_STORAGE_SECRET_KEY;if(!endpoint||!bucket||!accessKeyId||!secretAccessKey)throw new Error('MEDIA_STORAGE_NOT_CONFIGURED');const url=new URL(endpoint);if(process.env.NODE_ENV==='production'&&url.protocol!=='https:')throw new Error('MEDIA_STORAGE_HTTPS_REQUIRED');return{endpoint:url.toString(),bucket,accessKeyId,secretAccessKey,region:process.env.MEDIA_STORAGE_REGION||'auto'}}
function client(){const c=config();return{bucket:c.bucket,s3:new S3Client({endpoint:c.endpoint,region:c.region,forcePathStyle:process.env.MEDIA_STORAGE_FORCE_PATH_STYLE==='true',credentials:{accessKeyId:c.accessKeyId,secretAccessKey:c.secretAccessKey}})}}
function encodedCopySource(bucket:string,key:string){return`${encodeURIComponent(bucket)}/${key.split('/').map(encodeURIComponent).join('/')}`}
export async function createQuarantineUploadUrl(objectKey:string,contentType:string,byteSize:number){const{s3,bucket}=client();return getSignedUrl(s3,new PutObjectCommand({Bucket:bucket,Key:`quarantine/${objectKey}`,ContentType:contentType,ContentLength:byteSize}),{expiresIn:300})}
export async function readQuarantinedObject(objectKey:string,maxBytes:number){const{s3,bucket}=client();const r=await s3.send(new GetObjectCommand({Bucket:bucket,Key:`quarantine/${objectKey}`}));if(!r.Body)throw new Error('MEDIA_OBJECT_EMPTY');if(r.ContentLength!==undefined&&r.ContentLength>maxBytes)throw new Error('MEDIA_OBJECT_TOO_LARGE');const chunks:Uint8Array[]=[];let total=0;for await(const chunk of r.Body as AsyncIterable<Uint8Array>){total+=chunk.byteLength;if(total>maxBytes)throw new Error('MEDIA_OBJECT_TOO_LARGE');chunks.push(chunk)}const out=new Uint8Array(total);let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.byteLength}return out}
export async function deleteQuarantinedObject(objectKey:string){const{s3,bucket}=client();await s3.send(new DeleteObjectCommand({Bucket:bucket,Key:`quarantine/${objectKey}`}))}
export async function publishedObjectExists(objectKey:string){const{s3,bucket}=client();try{await s3.send(new HeadObjectCommand({Bucket:bucket,Key:`published/${objectKey}`}));return true}catch(e){const status=(e as{$metadata?:{httpStatusCode?:number}}).$metadata?.httpStatusCode;if(status===404)return false;throw e}}
export async function writePublishedObject(objectKey:string,contentType:string,bytes:Uint8Array){const{s3,bucket}=client(),destination=`published/${objectKey}`;if(!await publishedObjectExists(objectKey)){await s3.send(new PutObjectCommand({Bucket:bucket,Key:destination,Body:bytes,ContentType:contentType,ContentLength:bytes.byteLength,CacheControl:'private, max-age=31536000, immutable'}))}return destination}
export async function copyValidatedObjectToPublished(objectKey:string,contentType:string){const{s3,bucket}=client(),source=`quarantine/${objectKey}`,destination=`published/${objectKey}`;if(!await publishedObjectExists(objectKey)){await s3.send(new CopyObjectCommand({Bucket:bucket,Key:destination,CopySource:encodedCopySource(bucket,source),ContentType:contentType,MetadataDirective:'REPLACE'}))}return destination}
export async function promoteValidatedObject(objectKey:string,contentType:string){const destination=await copyValidatedObjectToPublished(objectKey,contentType);await deleteQuarantinedObject(objectKey);return destination}
