import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { pool } from './db.js';
export const uploadRequestSchema=z.object({invitationId:z.string().uuid(),category:z.enum(['IMAGE','AUDIO']),byteSize:z.number().int().positive(),contentType:z.string().min(1).max(100)}).strict();
const imageTypes=new Set(['image/jpeg','image/png','image/webp']),audioTypes=new Set(['audio/mpeg','audio/mp4','audio/ogg']);
export function validateUploadRequest(category:'IMAGE'|'AUDIO',byteSize:number,contentType:string){return category==='IMAGE'?byteSize<=8*1024*1024&&imageTypes.has(contentType):byteSize<=15*1024*1024&&audioTypes.has(contentType)}
export function detectMediaType(bytes:Uint8Array):string|null{const b0=bytes[0],b1=bytes[1],b2=bytes[2];if(bytes.length>=3&&b0===0xff&&b1===0xd8&&b2===0xff)return'image/jpeg';if(bytes.length>=8&&b0===0x89&&b1===0x50&&b2===0x4e&&bytes[3]===0x47&&bytes[4]===0x0d&&bytes[5]===0x0a&&bytes[6]===0x1a&&bytes[7]===0x0a)return'image/png';if(bytes.length>=12&&Buffer.from(bytes.subarray(0,4)).toString('ascii')==='RIFF'&&Buffer.from(bytes.subarray(8,12)).toString('ascii')==='WEBP')return'image/webp';if(bytes.length>=3&&Buffer.from(bytes.subarray(0,3)).toString('ascii')==='ID3')return'audio/mpeg';if(bytes.length>=2&&b0===0xff&&b1!==undefined&&(b1&0xe0)===0xe0)return'audio/mpeg';if(bytes.length>=12&&Buffer.from(bytes.subarray(4,8)).toString('ascii')==='ftyp')return'audio/mp4';if(bytes.length>=4&&Buffer.from(bytes.subarray(0,4)).toString('ascii')==='OggS')return'audio/ogg';return null}
export function validateMediaBytes(category:'IMAGE'|'AUDIO',declaredType:string,bytes:Uint8Array){const detected=detectMediaType(bytes);return detected!==null&&detected===declaredType&&validateUploadRequest(category,bytes.byteLength,detected)?detected:null}
export async function authorizeUpload(userId:string,input:z.infer<typeof uploadRequestSchema>){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');if(!validateUploadRequest(input.category,input.byteSize,input.contentType))return null;const r=await pool.query(`SELECT i.id,i.package_slug FROM invitations i JOIN orders o ON o.id=i.order_id WHERE i.id=$1 AND o.user_id=$2 LIMIT 1`,[input.invitationId,userId]);if(r.rowCount!==1)return null;if(input.category==='AUDIO'&&r.rows[0].package_slug==='HEMAT')return null;const objectKey=`${userId}/${input.invitationId}/${randomUUID()}`;await pool.query(`INSERT INTO media_uploads(id,invitation_id,user_id,object_key,category,declared_content_type,byte_size,status) VALUES($1,$2,$3,$4,$5,$6,$7,'QUARANTINED')`,[randomUUID(),input.invitationId,userId,objectKey,input.category,input.contentType,input.byteSize]);return{objectKey,status:'QUARANTINED'as const}}
export async function getQuarantinedUpload(userId:string,objectKey:string){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const r=await pool.query(`SELECT category,declared_content_type,byte_size FROM media_uploads WHERE user_id=$1 AND object_key=$2 AND status='QUARANTINED' LIMIT 1`,[userId,objectKey]);if(r.rowCount!==1)return null;return{category:r.rows[0].category as 'IMAGE'|'AUDIO',declaredContentType:String(r.rows[0].declared_content_type),byteSize:Number(r.rows[0].byte_size)}}
export async function markValidatedUpload(userId:string,objectKey:string,bytes:Uint8Array){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const r=await pool.query(`SELECT id,category,declared_content_type,byte_size FROM media_uploads WHERE user_id=$1 AND object_key=$2 AND status='QUARANTINED' LIMIT 1`,[userId,objectKey]);if(r.rowCount!==1)return null;const row=r.rows[0],detected=validateMediaBytes(row.category,row.declared_content_type,bytes);if(!detected||Number(row.byte_size)!==bytes.byteLength){await pool.query(`UPDATE media_uploads SET status='REJECTED',updated_at=now() WHERE id=$1 AND status='QUARANTINED'`,[row.id]);return null}await pool.query(`UPDATE media_uploads SET status='VALIDATED',validated_content_type=$2,updated_at=now() WHERE id=$1 AND status='QUARANTINED'`,[row.id,detected]);return{validatedContentType:detected,status:'VALIDATED'as const}}
export async function getUploadForPublication(userId:string,objectKey:string){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const r=await pool.query(`SELECT id,status,category,validated_content_type,byte_size FROM media_uploads WHERE user_id=$1 AND object_key=$2 AND status IN('VALIDATED','PUBLISHED') AND validated_content_type IS NOT NULL LIMIT 1`,[userId,objectKey]);if(r.rowCount!==1)return null;return{id:String(r.rows[0].id),status:r.rows[0].status as 'VALIDATED'|'PUBLISHED',category:r.rows[0].category as 'IMAGE'|'AUDIO',validatedContentType:String(r.rows[0].validated_content_type),byteSize:Number(r.rows[0].byte_size)}}
export async function getValidatedUploadForPublication(userId:string,objectKey:string){const x=await getUploadForPublication(userId,objectKey);return x?.status==='VALIDATED'?x:null}
export async function markUploadPublished(userId:string,objectKey:string){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const r=await pool.query(`UPDATE media_uploads SET status='PUBLISHED',updated_at=now() WHERE user_id=$1 AND object_key=$2 AND status='VALIDATED' RETURNING id`,[userId,objectKey]);if(r.rowCount===1)return true;const current=await pool.query(`SELECT 1 FROM media_uploads WHERE user_id=$1 AND object_key=$2 AND status='PUBLISHED' LIMIT 1`,[userId,objectKey]);return current.rowCount===1}
export function storageConfigured(){return Boolean(process.env.MEDIA_STORAGE_ENDPOINT&&process.env.MEDIA_STORAGE_BUCKET&&process.env.MEDIA_STORAGE_ACCESS_KEY&&process.env.MEDIA_STORAGE_SECRET_KEY)}
